### ISSUE TITLE
Can't I use pip3 instead of pip?

### ISSUE THREAD

**Issue by Banksy-said-hi** [victordlp8/OreMining#2]
Hey there!

I am having problem. My device works with pip3 and when run `pip install -r requirements.txt`, nothing actually happens. It says "command not found"

Best,
Banksy_said_hi

**Comment by VitorDecrypt** [comment]
install requirements separately

**Comment by victordlp8** [comment]
Use `pip3 install -r requirements.txt` that should work or just install requirements separately as said by Vitor
