### ISSUE TITLE
usage of pygetwindow..

### ISSUE THREAD

**Issue by mrprobz** [victordlp8/OreMining#5]
Seems ur last version does not support ubuntu.. 

local/lib/python3.10/site-packages/pygetwindow/__init__.py", line 347, in <module>
    raise NotImplementedError(
NotImplementedError: PyGetWindow currently does not support Linux. If you have Xlib knowledge, please contribute! https://github.com/asweigart/pygetwindow

Any other replacement package that could be used for pygetwindow? 
Thx

**Comment by tomiock** [comment]
This repo is meant for personal use and we do not plan to make it Unix compatible. Fork if you have any issues.
We are sorry for the inconvenience.

You may try to use https://github.com/Kalmat/PyWinCtl

**Comment by mrprobz** [comment]
thx

**Comment by victordlp8** [comment]
Now you should be able to use it without problems but doing Ctrl + C on the main terminal won't close all the deployed ones automatically.
