### ISSUE TITLE
 --priority-fee 30000000 claim

### ISSUE THREAD

**Issue by bashar1988** [victordlp8/OreMining#6]
can you please write the claim code for wsl2 iam using
ore --rpc (my rpc) --keypair ~/.config/solana/id.json --priority-fee 30000000 claim
but no sucsses

**Comment by victordlp8** [comment]
No, no custom command just for you sorry. If you want to change it edit the code or use the config.ini file

**Comment by bashar1988** [comment]
thank you for the replay i dont want a custom command for me, i want to know how or where i need to run the code / ore --keypair ore_keypair.json --priority-fee 25000000 claim / i using now the keeper.sy script and i dont know how to claim. thnak again for your time
